export type MockData = {
  titles: string[];
  descriptions: string[];
  createdDates: string[];
  previews: string[];
  photos: string[];
  citys: string[];
  houseTypes: string[];
  premium: string[];
  favorite: string[];
  ratings: string[];
  roomNumbers: string[];
  guests: string[];
  prices: string[];
  features: string[];
  authors: string[];
  coments: string[];
  coords: string[];
  names: string[];
  mails: string[];
  userTypes: string[];
};
